### ISSUE TITLE
Alignment with GDAL Zarr CRS conventions?

### ISSUE THREAD

**Issue by rabernat** [christophenoel/geozarr-spec#3]
Today I learned that GDAL uses its own convention for storing CRS which is incompatible with Xarray (via https://github.com/pydata/xarray/issues/6448)

https://gdal.org/drivers/raster/zarr.html

Given that GDAL is the most widely used library for processing raster data, it seems very important to align GeoZarr with what GDAL supports. I do not know the best way to resolve this issue; I am just raising it here to keep track of it.

**Comment by christophenoel** [comment]
Very well spotted. I think that GDAL will align if GeoZarr emerges as a standard. :)

**Comment by dwilson1988** [comment]
First off, very cool to see this coming along. My company has been using Zarr for the last couple years for large scale spatiotemporal data fusion work and have arrived at some similar conventions. We'd like to arrive on something that is both standard and meaningful for the larger geospatial community, so thank you very much for putting so much work into this spec.

The GeoZarr spec seems to have settled on the CF conventions, which works well for systems that are used to working with legacy NetCDF data. Unfortunately, I believe this limits the user base when it comes to spatial references. For the numerous systems out there that don't work as well with the CF Grid Mapping, would it be possible to include in this spec an alternative way of specifying the spatial reference? The emerging [GeoParquet](https://github.com/opengeospatial/geoparquet) standard, for example, has settled on the ProjJSON format, and WKT is pretty much universally used across the geospatial community as well. I believe this would fit better with the other OGC standard (though I'm not speaking for the OGC here). 

Would expanding this spec to include spatial references beyond CF Grid Mappings be on the table?

**Comment by rabernat** [comment]
Hi @dwilson1988 and thanks for chiming in.

Nothing is settled! 😄  We are in the process of convening and OGC SWG to formalize this spec as a standard, and during that process there will be an opportunity for folks to weigh in and propose changes. We will welcome your voice in that. I'll post an update here as soon as the SWG details are announced.

**Comment by dwilson1988** [comment]
Awesome, we'd love to participate in any discussions we could add value to!

**Comment by rouault** [comment]
> I think that GDAL will align if GeoZarr emerges as a standard. :)

It depends on what emerges :-) but yes the current status of the Geo part in the GDAL Zarr driver should be considered as experimental and can certainly evolve.
The reason I used WKT and/or PROJJSON for the CRS part was that, unfortunately, while GDAL handles the CF Grid Mapping in its netCDF driver, it looked very painful to extract that part of the code from the driver to be usable by both the netCDF and Zarr one. Putting an attribute with a WKT and/or PROJJSON was a much faster route...

**Comment by christophenoel** [comment]
The GeoZarr specification has been transferred to the Zarr-developers repository to facilitate collaborative work on the specification. https://github.com/zarr-developers/geozarr-spec
