### ISSUE TITLE
Present GeoZarr at the Pangeo Showcase?

### ISSUE THREAD

**Issue by rsignell-usgs** [christophenoel/geozarr-spec#4]
@christophenoel, I think it would be great to have a talk on GeoZarr as part of the Pangeo Showcase!  

 It's just a short 15-20 min presentation at the start of the weekly Pangeo meeting, but talks are recorded and given a DOI -- check out [previous Showcase talks](https://pangeo.io/pangeo-showcase.html)  

We are working on spinning up the Fall 2022 talks, and it would be great to have you! 

Would you be willing?

**Comment by christophenoel** [comment]
@rsignell-usgs Thanks a lot for the invitation. Unfortunately, I have a full dedication on unrelated projects, and I'm sorry to say I cannot manage to spend time on this topic. All apologies.

**Comment by christophenoel** [comment]
@rsignell-usgs  By the way, I will forward your invitation to ScanWorld and ConstellR companies who participated to the project from which GeoZarr emerged.

**Comment by rsignell-usgs** [comment]
@christophenoel okay, thanks!

**Comment by rsignell-usgs** [comment]
Just curious:  is geozarr alive and well (and being used) or is it now deprecated in favor of other specs?
